# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delegate_democracy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='proxy',
            old_name='issue_catergory',
            new_name='issue_category',
        ),
        migrations.AddField(
            model_name='voter',
            name='body_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delegate_democracy.Body'),
        ),
        migrations.AddField(
            model_name='issuecategory',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delegate_democracy.Body'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delegate_democracy.Body'),
        ),
        migrations.AddField(
            model_name='voter',
            name='body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delegate_democracy.Body'),
        ),
    ]
