# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delegate_democracy', '0003_auto_20170123_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
